adding git hub actions, reorganizing structure and documentation

diff --git a/.github/workflows/run_robot_tests.yml b/.github/workflows/run_robot_tests.yml
--- a/.github/workflows/run_robot_tests.yml
+++ b/.github/workflows/run_robot_tests.yml
@@ -27,6 +27,15 @@ jobs:
         echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
         echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
 
+    - name: Check KVM Support
+      run: |
+        if ! grep -qE "(vmx|svm)" /proc/cpuinfo; then
+          echo "KVM support is required to run the emulator. Exiting..."
+          exit 1
+        else
+          echo "KVM support detected. Proceeding..."
+        fi
+
     - name: Accept Licenses and Install Emulator
       run: |
         yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
